/**
 * This code was generated by the PartiQL I.R. Generator.
 * Do not modify this file.  [#-- Unless you're editing the template, of course! --]
 */
@file:Suppress("unused", "MemberVisibilityCanBePrivate", "FunctionName",
"CanBePrimaryConstructorProperty", "UNNECESSARY_SAFE_CALL",
"USELESS_ELVIS", "RemoveRedundantQualifierName", "LocalVariableName")

package ${namespace}

import com.amazon.ionelement.api.*
import org.partiql.pig.runtime.*

